version: '3.8'
services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
      MARIADB_DATABASE: 2k
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=dev
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/app
    entrypoint: uvicorn twok.api:app --host 0.0.0.0 --port 8000
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8000/health"
        ]
    depends_on:
      - db

  api-nginx:
    image: nginx
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./api_nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - apiserver

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/frontend:/usr/share/nginx/html
      - ${PWD}/uploads:/usr/share/nginx/html/uploads
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email 2kanna@pm.me --agree-tos --no-eff-email --keep-until-expiring --rsa-key-size 4096 --domains 2kanna.org
